version: 1.0.{build}
skip_commits:
 files:
   - docs/*
   - '**/*.html'
   - .travis.yml
skip_branch_with_pr: true
max_jobs: 6
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
shallow_clone: true
environment:
  # these variables are common to all jobs
  TOMOPY_USE_C_ALGORITHMS: "1"
  matrix:
    - PYTHON_VERSION: "36"
      MINICONDA: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "37"
      MINICONDA: "C:\\Miniconda37-x64"
matrix:
  fast_finish: true
install:
  - "%MINICONDA%\\Scripts\\activate.bat"
  - conda activate base
  - conda config --set always_yes True
  - conda update -n base conda
  - conda env create -n tomopy -f envs/win-%PYTHON_VERSION%.yml
  - conda activate tomopy
  - conda info -a
  - conda list --explicit
  # Check the compilers
  - where gcc
  - where g++
platform: x64
configuration: Debug
build_script:
  - set CC=gcc
  - set CXX=g++
  - python setup.py install
test_script:
  - nosetests
