language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
sudo: false
env:
  global:
    - PATH=${HOME}/miniconda/bin:${PATH}
    - LD_LIBRARY_PATH=${HOME}/miniconda/lib
    - PYCTEST_ARGS='--pyctest-submit --pyctest-jobs=1 --pyctest-site=Travis'
    - TOMOPY_USE_C_SIRT=1
    - TOMOPY_USE_C_MLEM=1
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - conda config --set always_yes yes
install:
  - PYTHON_TAG=$(echo ${TRAVIS_PYTHON_VERSION} | sed 's/\.//g')
  - conda env create -n tomopy -f envs/tomopy-python${PYTHON_TAG}.yml
  - source activate tomopy
  - conda info -a
  - conda list --explicit
  - ./pyctest_tomopy.py --disable-phantom-tests --disable-gpu --disable-cuda ${PYCTEST_ARGS}
script:
  - coverage run $(which nosetests)
after_success:
  - coveralls
