language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
sudo: false
env:
  - PATH=${HOME}/miniconda/bin:${PATH} LD_LIBRARY_PATH=${HOME}/miniconda/lib
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - conda config --add channels conda-forge
  - conda config --add channels jrmadsen
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
install:
  - "conda install python=${TRAVIS_PYTHON_VERSION} nose six numpy scipy
    scikit-image scikit-build mkl-devel mkl_fft python-coveralls
    dxchange numexpr coverage timemory pyctest"
  - export CC=$(which gcc)
  - export CXX=$(which g++)
  - echo "CC = ${CC}, CXX = ${CXX}"
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install futures;
    fi
  - conda info -a
  - conda list --explicit
  - ./pyctest_tomopy.py --pyctest-site=Travis --pyctest-submit --pyctest-jobs=1 --disable-phantom-tests -- -VV
script:
  - coverage run $(which nosetests)
after_success:
  - coveralls
